version: '3.4'

services:
  gateway.mobile:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  gateway.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  customer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
